version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - sentinel-net

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - sentinel-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - sentinel-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - sentinel-net

  app:
    build: .
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge
